### ISSUE TITLE
implement min/max normalisation

### ISSUE THREAD

**Issue by olgeet** [giuliaripellino/GOAR-ML-Project#26]

**Comment by gallenaxel** [comment]
Implemented scaling and un-scaling function, such that the variables all lie in the range of [0,1] instead of [min,max]. Implemented [here](https://github.com/giuliaripellino/GOAR-ML-Project/commit/696d62ef6cadc22ce83cf3e2446bb906c2ebe645) and the README has also been updated [here](https://github.com/giuliaripellino/GOAR-ML-Project/commit/bef304096c84c210225ac844f4e57c845437b1c7)


![Screenshot 2024-03-16 at 15 56 11](https://github.com/giuliaripellino/GOAR-ML-Project/assets/74319950/3e45d47e-5016-41e6-a15a-af3409d9c517)
